services:
  db:
    image: postgres:16-alpine
    container_name: furniture_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: furniture_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI (http://localhost:8025)

  web:
    build: .
    container_name: furniture_web
    env_file: .env
    environment:
      EMAIL_HOST: mailhog
      EMAIL_PORT: "1025"
      EMAIL_USE_TLS: "0"
      EMAIL_USE_SSL: "0"
      DEFAULT_FROM_EMAIL: "no-reply@furniture.local"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - mailhog

volumes:
  pgdata:
