# Generated by Django 5.2.5 on 2025-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='furniture',
            index=models.Index(fields=['category'], name='shop_furnit_categor_dbbf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='shop_order_email_fa7dab_idx'),
        ),
    ]
